---
- name: apache install and configure play
  hosts: webservers
  tasks:
   - name: httpd install
     ansible.builtin.dnf:
       name: httpd
       state: present
   - name: service httpd start
     ansible.builtin.service:
       name: httpd
       state: started
       enabled: true
   - name: indexfile set
     ansible.builtin.template:
       src: index.j2
       dest: /var/www/html/index.html
           
